import React, { useEffect, useState } from "react";
import { doc, getDoc, updateDoc } from "firebase/firestore";
import { db } from "../../../firebaseConfig";
import {
  DollarSign,
  FileText,
  Plus,
  Trash2,
  Save,
  CheckCircle2,
} from "lucide-react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { Users, Calendar, CheckCircle, XCircle, Printer } from "lucide-react";

const ServiceFeeAndPolicyPanel = () => {
  const [serviceFee, setServiceFee] = useState("");
  const [policies, setPolicies] = useState([]);
  const [newPolicy, setNewPolicy] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [hosts, setHosts] = useState([]);
  const [hostFilter, setHostFilter] = useState("All");
  const [loadingHosts, setLoadingHosts] = useState(false);
  const subscribedCount = hosts.filter((h) => h.subscribed).length;
  const unsubscribedCount = hosts.filter((h) => !h.subscribed).length;

  const filteredHosts = hosts.filter((h) => {
    if (hostFilter === "All") return true;
    if (hostFilter === "Subscribed") return h.subscribed === true;
    if (hostFilter === "Unsubscribed") return h.subscribed !== true;
    return true;
  });

  const handlePrintHostReport = async () => {
    try {
      const printWindow = window.open("", "_blank", "width=1000,height=700");
      const reportHTML = `
      <html>
        <head>
          <title>KuboHub | Host Subscription Report</title>
          <style>
            body {
              font-family: 'Segoe UI', sans-serif;
              margin: 40px;
              background: #fdfcfb;
              color: #333;
            }
            h1 {
              text-align: center;
              color: #1a3a2b;
              text-transform: uppercase;
              margin-bottom: 20px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
              font-size: 15px;
            }
            th, td {
              border: 1px solid #ccc;
              padding: 10px;
              text-align: left;
            }
            th {
              background-color: #f0f8f2;
              color: #1a3a2b;
            }
            tr:nth-child(even) {
              background-color: #fafafa;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              color: #555;
            }
          </style>
        </head>
        <body>
          <h1>HOST SUBSCRIPTION REPORT</h1>
          <p><strong>Filter:</strong> ${hostFilter}</p>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Host Name</th>
                <th>Next Billing Date</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${
                filteredHosts.length === 0
                  ? `<tr><td colspan="4" style="text-align:center;">No hosts found</td></tr>`
                  : filteredHosts
                      .map(
                        (h, i) => `
                    <tr>
                      <td>${i + 1}</td>
                      <td>${h.fullName || h.name || "Unnamed Host"}</td>
                      <td>${formatNextBilling(h.nextbilling)}</td>
                      <td>${h.subscribed ? "Subscribed" : "Not Subscribed"}</td>
                    </tr>
                  `
                      )
                      .join("")
              }
            </tbody>
          </table>
          <div class="footer">
            Generated by <strong>KuboHub Admin</strong> • ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `;
      printWindow.document.open();
      printWindow.document.write(reportHTML);
      printWindow.document.close();
      printWindow.print();
    } catch (error) {
      console.error("Error printing host report:", error);
      alert("Failed to generate host report.");
    }
  };

  const formatNextBilling = (code) => {
    if (!code || code.length !== 6) return "N/A";
    const [mm, dd, yy] = [code.slice(0, 2), code.slice(2, 4), code.slice(4, 6)];
    const fullYear = 2000 + Number(yy);
    const date = new Date(`${fullYear}-${mm}-${dd}`);
    return date.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  };

  const handlePrintPolicyContract = async () => {
    try {
      const ref = doc(db, "servicepolicy", "main");
      const snap = await getDoc(ref);

      if (!snap.exists()) {
        alert("No policy data found.");
        return;
      }

      const data = snap.data();
      const policiesList = data.policies || [];
      const serviceFeeAmount = data.servicefee || 0;

      const printWindow = window.open("", "_blank", "width=900,height=700");

      const reportHTML = `
      <html>
        <head>
          <title>KuboHub | Host Policy Contract</title>
          <style>
            body {
              font-family: 'Segoe UI', sans-serif;
              margin: 60px;
              background: #fdfcfb;
              color: #333;
              line-height: 1.7;
            }
            header {
              text-align: center;
              margin-bottom: 40px;
            }
            h1 {
              font-size: 26px;
              color: #1a3a2b;
              text-transform: uppercase;
              letter-spacing: 1px;
              margin-bottom: 8px;
            }
            h2 {
              font-size: 15px;
              color: #555;
              margin-top: 4px;
            }
            p.intro {
              margin-bottom: 24px;
              font-size: 15px;
              color: #444;
              text-align: justify;
            }
            ul {
              list-style-type: disc;
              padding-left: 30px;
              margin-top: 10px;
            }
            li {
              margin-bottom: 10px;
              font-size: 15px;
              color: #222;
            }
            .fee-box {
              margin-top: 40px;
              background: #f0f8f2;
              border: 1px solid #d8f3dc;
              padding: 15px 25px;
              border-radius: 12px;
              font-size: 16px;
              font-weight: bold;
              color: #1a3a2b;
              text-align: center;
            }
            footer {
              margin-top: 80px;
              text-align: center;
              font-size: 14px;
              color: #555;
            }
            .signature {
              margin-top: 80px;
              text-align: center;
            }
            .signature-line {
              border-top: 1px solid #000;
              width: 300px;
              margin: 40px auto 5px;
            }
          </style>
        </head>
        <body>
          <header>
            <h1>KUBOHUB HOST TERMS AND POLICIES</h1>
            <h2>Effective as of ${new Date().toLocaleDateString()}</h2>
          </header>

          <p class="intro">
            Please comply with the following terms and conditions set forth by KuboHub. 
            These policies are created to ensure a safe, transparent, and fair environment 
            between hosts and guests. By continuing to use the KuboHub platform, you agree 
            to adhere to all the policies stated below.
          </p>

          <ul>
            ${policiesList
              .map((p) => `<li>${p.replace(/\n/g, "<br>")}</li>`)
              .join("")}
          </ul>

          <div class="fee-box">
            <strong>Monthly Subscription Fee:</strong> ₱${Number(
              serviceFeeAmount
            ).toLocaleString()}
          </div>

          <div class="signature">
            <div class="signature-line"></div>
            <div>Signature over Printed Name</div>
          </div>

          <footer>
            Generated by <strong>KuboHub Admin</strong> • ${new Date().toLocaleString()}
          </footer>
        </body>
      </html>
    `;

      printWindow.document.open();
      printWindow.document.write(reportHTML);
      printWindow.document.close();
      printWindow.print();
    } catch (error) {
      console.error("Error printing policy report:", error);
      alert("Failed to generate policy report.");
    }
  };

  useEffect(() => {
  const fetchHosts = async () => {
    try {
      setLoadingHosts(true);
      const q = query(collection(db, "users"), where("role", "==", "host"));
      const snap = await getDocs(q);
      const today = new Date();

      const updatedHosts = await Promise.all(
        snap.docs.map(async (docSnap) => {
          const host = { id: docSnap.id, ...docSnap.data() };
          const code = host.nextbilling;

          // Check date validity
          if (code && code.length === 6) {
            const mm = code.slice(0, 2);
            const dd = code.slice(2, 4);
            const yy = code.slice(4, 6);
            const billingDate = new Date(`20${yy}-${mm}-${dd}`);

            // Compare today's date vs billing date
            if (today >= billingDate && host.subscribed === true) {
              // Update Firestore if past due
              await updateDoc(doc(db, "users", host.id), {
                subscribed: false,
              });
              host.subscribed = false; // reflect in UI immediately
            }
          }

          return host;
        })
      );

      setHosts(updatedHosts);
    } catch (error) {
      console.error("Error fetching or updating hosts:", error);
    } finally {
      setLoadingHosts(false);
    }
  };

  fetchHosts();
}, []);


  // Load settings from Firestore
  useEffect(() => {
    const loadSettings = async () => {
      try {
        const ref = doc(db, "servicepolicy", "main");
        const snap = await getDoc(ref);

        if (snap.exists()) {
          const data = snap.data();
          setServiceFee(data.servicefee ?? "");
          setPolicies(data.policies ?? []); // array of policy strings
        }
      } catch (error) {
        console.error("Error loading service policy:", error);
      } finally {
        setLoading(false);
      }
    };

    loadSettings();
  }, []);

  // Save changes
  const handleSave = async () => {
    try {
      setSaving(true);
      setSaved(false);
      const ref = doc(db, "servicepolicy", "main");

      await updateDoc(ref, {
        servicefee: Number(serviceFee),
        policies: policies,
      });

      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (error) {
      console.error("Error updating service policy:", error);
      alert("Failed to update. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  const handleAddPolicy = () => {
    if (!newPolicy.trim()) return;
    setPolicies([...policies, newPolicy.trim()]);
    setNewPolicy("");
  };

  const handleDeletePolicy = (index) => {
    setPolicies(policies.filter((_, i) => i !== index));
  };

  const handleUpdatePolicy = (index, value) => {
    const updated = [...policies];
    updated[index] = value;
    setPolicies(updated);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-slate-600 font-medium">Loading settings...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 py-6 px-4 sm:py-8 sm:px-6 lg:py-12 lg:px-8">
      <div className="max-w-5xl mx-auto space-y-8">
        {/* ===== SERVICE CONFIGURATION CARD ===== */}
        <div>
          {/* Header */}
          <div className="mb-6 sm:mb-8">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 sm:w-12 sm:h-12 bg-gradient-to-br from-emerald-500 to-emerald-600 rounded-2xl flex items-center justify-center shadow-lg">
                <FileText className="w-5 h-5 sm:w-6 sm:h-6 text-white" />
              </div>
              <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-slate-800">
                Service Configuration
              </h1>
            </div>
            <p className="text-slate-600 text-sm sm:text-base lg:text-lg">
              Manage your monthly service fees and compliance policies
            </p>
          </div>

          {/* Main Card */}
          <div className="bg-white rounded-2xl sm:rounded-3xl shadow-xl border border-slate-200 overflow-hidden">
            <div className="h-1.5 bg-gradient-to-r from-emerald-500 via-emerald-600 to-teal-600"></div>

            <div className="p-4 sm:p-6 lg:p-10">
              {/* Service Fee Section */}
              <div className="mb-8 sm:mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 sm:w-10 sm:h-10 bg-emerald-100 rounded-xl flex items-center justify-center">
                    <DollarSign className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-600" />
                  </div>
                  <div>
                    <label className="block text-slate-800 font-bold text-lg sm:text-xl">
                      Monthly Service Fee
                    </label>
                    <p className="text-xs sm:text-sm text-slate-500">
                      Set your monthly hosting fee
                    </p>
                  </div>
                </div>

                <div className="relative group">
                  <span className="absolute left-4 sm:left-5 top-1/2 -translate-y-1/2 text-slate-400 font-bold text-lg sm:text-xl group-focus-within:text-emerald-600 transition-colors">
                    ₱
                  </span>
                  <input
                    type="number"
                    value={serviceFee}
                    onChange={(e) => setServiceFee(e.target.value)}
                    placeholder="0.00"
                    className="w-full border-2 border-slate-200 rounded-xl sm:rounded-2xl pl-10 sm:pl-12 pr-4 sm:pr-6 py-4 sm:py-5 text-lg sm:text-xl font-bold outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 transition-all bg-slate-50 focus:bg-white"
                  />
                </div>
              </div>

              <div className="relative my-8 sm:my-12">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t-2 border-slate-200"></div>
                </div>
                <div className="relative flex justify-center">
                  <span className="bg-white px-4 text-xs sm:text-sm font-semibold text-slate-400 uppercase tracking-wider">
                    Policies
                  </span>
                </div>
              </div>

              {/* Policies Section */}
              <div>
                <div className="flex items-center gap-3 mb-4 sm:mb-6">
                  <div className="w-9 h-9 sm:w-10 sm:h-10 bg-teal-100 rounded-xl flex items-center justify-center">
                    <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-teal-600" />
                  </div>
                  <div>
                    <label className="block text-slate-800 font-bold text-lg sm:text-xl">
                      Host Policies
                    </label>
                    <p className="text-xs sm:text-sm text-slate-500">
                      Displayed during guest registration
                    </p>
                  </div>
                </div>

                {/* Existing Policies */}
                {policies.length > 0 ? (
                  <div className="space-y-3 sm:space-y-4 mb-4 sm:mb-6 overflow-y-auto pr-2 max-h-[300px] sm:max-h-[350px]">
                    {policies.map((policy, index) => (
                      <div
                        key={index}
                        className="group relative bg-gradient-to-br from-slate-50 to-slate-100 border-2 border-slate-200 rounded-xl sm:rounded-2xl p-4 sm:p-5 hover:border-emerald-300 hover:shadow-md transition-all"
                      >
                        <div className="flex items-start gap-3 sm:gap-4">
                          <div className="flex-shrink-0 w-7 h-7 sm:w-8 sm:h-8 bg-emerald-500 text-white rounded-lg flex items-center justify-center font-bold text-xs sm:text-sm mt-1">
                            {index + 1}
                          </div>

                          <textarea
                            value={policy}
                            onChange={(e) => handleUpdatePolicy(index, e.target.value)}
                            rows={2}
                            className="flex-1 bg-transparent outline-none resize-none text-slate-700 font-medium leading-relaxed text-sm sm:text-base"
                          />

                          <button
                            onClick={() => handleDeletePolicy(index)}
                            className="flex-shrink-0 w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-white border-2 border-slate-200 flex items-center justify-center text-red-500 hover:bg-red-50 hover:border-red-300 transition-all opacity-100 sm:opacity-0 sm:group-hover:opacity-100"
                            title="Delete policy"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="mb-4 sm:mb-6 p-6 sm:p-8 bg-slate-50 border-2 border-dashed border-slate-300 rounded-xl sm:rounded-2xl text-center">
                    <FileText className="w-10 h-10 sm:w-12 sm:h-12 text-slate-400 mx-auto mb-3" />
                    <p className="text-slate-500 font-medium text-sm sm:text-base">No policies yet</p>
                    <p className="text-xs sm:text-sm text-slate-400">
                      Add your first policy below
                    </p>
                  </div>
                )}

                {/* Add New Policy */}
                <div className="bg-gradient-to-br from-emerald-50 to-teal-50 border-2 border-emerald-200 rounded-xl sm:rounded-2xl p-4 sm:p-6 shadow-sm">
                  <div className="flex items-center gap-2 mb-3">
                    <Plus className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-600" />
                    <span className="font-bold text-slate-700 text-sm sm:text-base">
                      Add New Policy
                    </span>
                  </div>

                  <textarea
                    rows={3}
                    value={newPolicy}
                    onChange={(e) => setNewPolicy(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && e.ctrlKey) {
                        handleAddPolicy();
                      }
                    }}
                    placeholder="Type your policy here... (Ctrl+Enter to add)"
                    className="w-full outline-none resize-none bg-white border-2 border-slate-200 rounded-xl p-3 sm:p-4 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100 transition-all text-sm sm:text-base"
                  />

                  <button
                    onClick={handleAddPolicy}
                    disabled={!newPolicy.trim()}
                    className="mt-3 bg-gradient-to-r from-emerald-500 to-emerald-600 text-white px-5 sm:px-6 py-2.5 sm:py-3 rounded-xl hover:from-emerald-600 hover:to-emerald-700 disabled:from-slate-300 disabled:to-slate-400 disabled:cursor-not-allowed font-semibold shadow-lg hover:shadow-xl transition-all flex items-center gap-2 text-sm sm:text-base"
                  >
                    <Plus className="w-4 h-4" />
                    Add Policy
                  </button>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="mt-6 sm:mt-8 space-y-3">
                {/* Save Button */}
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className={`w-full py-4 sm:py-5 rounded-xl sm:rounded-2xl font-bold text-white text-base sm:text-lg transition-all flex items-center justify-center gap-3 ${
                    saving
                      ? 'bg-slate-400 cursor-not-allowed'
                      : 'bg-gradient-to-r from-emerald-500 via-emerald-600 to-teal-600 hover:scale-[1.02] shadow-xl hover:shadow-2xl active:scale-[0.98]'
                  }`}
                >
                  {saving ? (
                    <>
                      <div className="w-5 h-5 border-3 border-white border-t-transparent rounded-full animate-spin"></div>
                      Saving Changes...
                    </>
                  ) : (
                    <>
                      <Save className="w-5 h-5" />
                      Save Changes
                    </>
                  )}
                </button>

                {/* Print Policy Contract Button */}
                <button
                  onClick={handlePrintPolicyContract}
                  className="no-print w-full px-5 sm:px-6 py-3.5 sm:py-4 bg-white border-2 border-emerald-500 text-emerald-600 rounded-xl sm:rounded-2xl font-semibold shadow-md hover:bg-emerald-50 hover:shadow-lg hover:scale-[1.02] transition-all flex items-center justify-center gap-2 text-sm sm:text-base"
                >
                  <Printer className="w-4 h-4 sm:w-5 sm:h-5" />
                  Print Policy Contract
                </button>

                {/* Success Message */}
                {saved && (
                  <div className="p-4 bg-emerald-50 border-2 border-emerald-200 rounded-xl flex items-center justify-center gap-3">
                    <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                    <p className="text-emerald-700 font-semibold text-sm sm:text-base">
                      Changes saved successfully!
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Helper Text */}
          <div className="mt-4 text-center">
            <p className="text-slate-500 text-xs sm:text-sm">
              Changes will be reflected immediately after saving
            </p>
          </div>
        </div>

        {/* ===== HOST SUBSCRIPTION MANAGEMENT ===== */}
        <div>
          {/* Header Section */}
          <div className="mb-6">
            <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4 mb-6">
              <div>
                <h2 className="text-2xl sm:text-3xl font-bold text-slate-800 flex items-center gap-3 mb-2">
                  <Users className="w-7 h-7 sm:w-8 sm:h-8 text-emerald-600" />
                  Host Subscriptions
                </h2>
                <p className="text-slate-600 text-xs sm:text-sm">
                  Manage and monitor host subscription status
                </p>
              </div>

              {/* Print Button */}
              <button
                onClick={handlePrintHostReport}
                className="no-print w-full sm:w-auto px-5 sm:px-6 py-3 bg-gradient-to-r from-emerald-500 to-emerald-600 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl hover:scale-[1.02] transition-all flex items-center justify-center gap-2 text-sm"
              >
                <Printer className="w-4 h-4" />
                Print Report
              </button>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
              <div className="bg-white rounded-xl p-4 shadow-md border border-slate-200">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs font-medium text-slate-500 uppercase mb-1">
                      Total Hosts
                    </p>
                    <p className="text-2xl font-bold text-slate-800">
                      {hosts.length}
                    </p>
                  </div>
                  <Users className="w-10 h-10 text-slate-400" />
                </div>
              </div>
              <div className="bg-emerald-50 rounded-xl p-4 shadow-md border border-emerald-200">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs font-medium text-emerald-700 uppercase mb-1">
                      Subscribed
                    </p>
                    <p className="text-2xl font-bold text-emerald-700">
                      {subscribedCount}
                    </p>
                  </div>
                  <CheckCircle className="w-10 h-10 text-emerald-400" />
                </div>
              </div>
              <div className="bg-red-50 rounded-xl p-4 shadow-md border border-red-200">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs font-medium text-red-700 uppercase mb-1">
                      Unsubscribed
                    </p>
                    <p className="text-2xl font-bold text-red-700">
                      {unsubscribedCount}
                    </p>
                  </div>
                  <XCircle className="w-10 h-10 text-red-400" />
                </div>
              </div>
            </div>

            {/* Filter Buttons */}
            <div className="flex flex-wrap gap-2">
              {['All', 'Subscribed', 'Unsubscribed'].map((filter) => (
                <button
                  key={filter}
                  onClick={() => setHostFilter(filter)}
                  className={`px-4 py-2.5 rounded-lg text-sm font-semibold transition-all ${
                    hostFilter === filter
                      ? 'bg-emerald-600 text-white shadow-md scale-[1.02]'
                      : 'bg-white text-slate-700 hover:bg-slate-50 shadow-sm border border-slate-200'
                  }`}
                >
                  {filter}
                </button>
              ))}
            </div>
          </div>

          {/* Desktop Table View */}
          <div className="hidden md:block overflow-hidden border border-slate-200 rounded-xl shadow-lg bg-white">
            <table className="min-w-full text-sm">
              <thead className="bg-gradient-to-r from-slate-100 to-slate-50">
                <tr>
                  <th className="px-6 py-4 text-left font-semibold text-slate-700">#</th>
                  <th className="px-6 py-4 text-left font-semibold text-slate-700">Host Name</th>
                  <th className="px-6 py-4 text-left font-semibold text-slate-700">Next Billing Date</th>
                  <th className="px-6 py-4 text-left font-semibold text-slate-700">Status</th>
                </tr>
              </thead>
              <tbody>
                {loadingHosts ? (
                  <tr>
                    <td colSpan="4" className="text-center py-12 text-slate-500">
                      <div className="flex flex-col items-center gap-2">
                        <div className="w-8 h-8 border-4 border-emerald-600 border-t-transparent rounded-full animate-spin"></div>
                        <p>Loading hosts...</p>
                      </div>
                    </td>
                  </tr>
                ) : filteredHosts.length === 0 ? (
                  <tr>
                    <td colSpan="4" className="text-center py-12 text-slate-500">
                      No hosts found for the selected filter.
                    </td>
                  </tr>
                ) : (
                  filteredHosts.map((h, i) => (
                    <tr key={h.id} className="border-t border-slate-100 hover:bg-slate-50 transition-all">
                      <td className="px-6 py-4 text-slate-600 font-medium">{i + 1}</td>
                      <td className="px-6 py-4">
                        <span className="font-semibold text-slate-800">
                          {h.name || h.fullName || 'Unnamed Host'}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-slate-600">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4 text-slate-400" />
                          {formatNextBilling(h.nextbilling)}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        {h.subscribed ? (
                          <span className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-emerald-100 text-emerald-700 rounded-full">
                            <CheckCircle className="w-3.5 h-3.5" />
                            Subscribed
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-red-100 text-red-600 rounded-full">
                            <XCircle className="w-3.5 h-3.5" />
                            Unsubscribed
                          </span>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {/* Mobile Card View */}
          <div className="md:hidden space-y-4">
            {loadingHosts ? (
              <div className="bg-white rounded-xl p-8 shadow-sm text-center">
                <div className="flex flex-col items-center gap-2">
                  <div className="w-8 h-8 border-4 border-emerald-600 border-t-transparent rounded-full animate-spin"></div>
                  <p className="text-slate-500">Loading hosts...</p>
                </div>
              </div>
            ) : filteredHosts.length === 0 ? (
              <div className="bg-white rounded-xl p-8 shadow-sm text-center text-slate-500">
                No hosts found for the selected filter.
              </div>
            ) : (
              filteredHosts.map((h, i) => (
                <div
                  key={h.id}
                  className="bg-white rounded-xl p-5 shadow-md border border-slate-200 hover:shadow-lg transition-all"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-bold text-slate-400">#{i + 1}</span>
                        <span className="text-lg font-bold text-slate-800">
                          {h.name || h.fullName || 'Unnamed Host'}
                        </span>
                      </div>
                    </div>
                    {h.subscribed ? (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold bg-emerald-100 text-emerald-700 rounded-full">
                        <CheckCircle className="w-3 h-3" />
                        Active
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold bg-red-100 text-red-600 rounded-full">
                        <XCircle className="w-3 h-3" />
                        Inactive
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-2 text-sm text-slate-600">
                    <Calendar className="w-4 h-4 text-slate-400" />
                    <span className="font-medium">Next Billing:</span>
                    <span>{formatNextBilling(h.nextbilling)}</span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      <style>{`
        @media print {
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
};

export default ServiceFeeAndPolicyPanel;
